Console.ForegroundColor = ConsoleColor.Cyan;
Console.WriteLine("ВИЗИТКА СИСТЕМЫ");
Console.ResetColor();
string studentName = "Dasha";
string studentGroup = "ПМБ-261";
string favLanguage = "С#";
string codingYears = "0";
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("\n[Студент]");
Console.ResetColor();
Console.WriteLine($"Имя:     {studentName}");
Console.WriteLine($"Группа:  {studentGroup}");
Console.WriteLine($"Дата:    {DateTime.Now:dd.MM.yyyy HH:mm}");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("\n[Компьютер]");
Console.ResetColor();
Console.WriteLine($"Имя машины:   {Environment.MachineName}");
Console.WriteLine($"Пользователь: {Environment.UserName}");
Console.WriteLine($"OC:           {Environment.OSVersion}");
Console.WriteLine($"64-битная OC: {Environment.Is64BitOperatingSystem}");
Console.WriteLine($"Версия .NET:  {Environment.Version}");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("\n[Процессор]");
Console.ResetColor();
Console.WriteLine($"Логических ядер: {Environment.ProcessorCount}");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("\n[Память]");
Console.ResetColor();
long workingSetMb = Environment.WorkingSet / 1024 / 1024;
Console.WriteLine($"Память процесса: {workingSetMb} МБ");
Console.WriteLine($"Размер указателя: {IntPtr.Size * 8} бит");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("\n[Все цвета консоли]");
Console.ResetColor();
foreach (ConsoleColor color in Enum.GetValues(typeof(ConsoleColor))) { Console.ForegroundColor = color; Console.WriteLine($"{color} - текст этим цветом"); }
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("\nПрограмма выполнена успешно! ");
Console.ResetColor();
Console.ReadKey();
